package com.example.KotlinBasic

class MethodCalling {



    fun main() {
        //Taken from user
        val otp = 5000


        //Taking user name from UI
        val userName = "ADMIN"
        val password = "password"

        printMyDetails()

//        checkMyUserName("admin")
        val a = checkMyUserName(userName)
        println(a)

//        val generatedOTPInMain = createOTP()
//
//
//        if (otp == generatedOTPInMain) {
//            System.err.println("true case")
//        }
//        else {
//            System.err.println("false case")
//        }


    }


    fun printMyDetails() {
        val a = "Name is Sujith"
       println(a)
    }

    fun createOTP(): Int {
//        generated by system
        val generatedOTP = 5000
        return generatedOTP
    }

    fun checkMyUserName(a: String): Boolean {

        println(a)
//        if (a  == "admin") {
//            println("true case")
//        }
//        userName


        if (a.equals("admin", ignoreCase = true)) {
            println("this is true case")
            return true
            //function is not possivble
        }
        else {
            //invalid user name
            println("false case")
            return false
            //function is not possible
        }


    }
}